<?php declare(strict_types=1);
/*
 * (c) shopware AG <info@shopware.com>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    0 => [
        'name' => 'categorydate1',
        'type' => 'date',
        '_locale' => 'de-DE',
        'configuration' => [
            'id' => '25',
            'table_name' => 's_categories_attributes',
            'column_name' => 'categorydate1',
            'column_type' => 'date',
            'default_value' => null,
            'position' => '0',
            'translatable' => '0',
            'display_in_backend' => '1',
            'custom' => '1',
            'help_text' => '',
            'support_text' => '',
            'label' => 'KategorieDatum1',
            'entity' => '',
            'array_store' => '',
        ],
    ],

    1 => [
        'name' => 'checkbox1',
        'type' => 'integer',
        '_locale' => 'de-DE',
        'configuration' => [
            'id' => '13',
            'table_name' => 's_articles_attributes',
            'column_name' => 'checkbox1',
            'column_type' => 'boolean',
            'default_value' => null,
            'position' => '0',
            'translatable' => '0',
            'display_in_backend' => '1',
            'custom' => '1',
            'help_text' => 'Meine HIlfe123',
            'support_text' => 'Supporttext123',
            'label' => 'MeineCheckbox1',
            'entity' => '',
            'array_store' => '',
        ],
    ],

    2 => [
        'name' => 'datetime1',
        'type' => 'datetime',
        '_locale' => 'de-DE',
        'configuration' => [
            'id' => '19',
            'table_name' => 's_articles_attributes',
            'column_name' => 'datetime1',
            'column_type' => 'datetime',
            'default_value' => null,
            'position' => '0',
            'translatable' => '0',
            'display_in_backend' => '1',
            'custom' => '1',
            'help_text' => '',
            'support_text' => '',
            'label' => 'Datum und Zeit',
            'entity' => '',
            'array_store' => '',
        ],
    ],

    3 => [
        'name' => 'attr6',
        'type' => 'text',
        '_locale' => 'de-DE',
        'configuration' => null,
    ],

    4 => [
        'name' => 'ganzzahlattr',
        'type' => 'integer',
        '_locale' => 'de-DE',
        'configuration' => [
            'id' => '4',
            'table_name' => 's_articles_attributes',
            'column_name' => 'ganzzahlattr',
            'column_type' => 'integer',
            'default_value' => null,
            'position' => '0',
            'translatable' => '0',
            'display_in_backend' => '1',
            'custom' => '1',
            'help_text' => '',
            'support_text' => '',
            'label' => 'Ganzzahlattribut',
            'entity' => '',
            'array_store' => '',
        ],
    ],

    5 => [
        'name' => 'dezimalzahl1',
        'type' => 'float',
        '_locale' => 'de-DE',
        'configuration' => [
            'id' => '7',
            'table_name' => 's_articles_attributes',
            'column_name' => 'dezimalzahl1',
            'column_type' => 'float',
            'default_value' => null,
            'position' => '0',
            'translatable' => '0',
            'display_in_backend' => '1',
            'custom' => '1',
            'help_text' => '',
            'support_text' => '',
            'label' => 'MeineDezimalzahl',
            'entity' => '',
            'array_store' => '',
        ],
    ],

    6 => [
        'name' => 'mediumtext1',
        'type' => 'text',
        '_locale' => 'de-DE',
        'configuration' => [
            'id' => '10',
            'table_name' => 's_articles_attributes',
            'column_name' => 'mediumtext1',
            'column_type' => 'html',
            'default_value' => null,
            'position' => '0',
            'translatable' => '0',
            'display_in_backend' => '1',
            'custom' => '1',
            'help_text' => '',
            'support_text' => '',
            'label' => 'Mediumtext',
            'entity' => '',
            'array_store' => '',
        ],
    ],
    7 => [
        'name' => 'combobox1',
        'type' => 'text',
        '_locale' => 'de-DE',
        'configuration' => [
            'id' => '22',
            'table_name' => 's_articles_attributes',
            'column_name' => 'combobox1',
            'column_type' => 'combobox',
            'default_value' => null,
            'position' => '0',
            'translatable' => '0',
            'display_in_backend' => '1',
            'custom' => '1',
            'help_text' => 'Mein HilfeText',
            'support_text' => 'Mein Supporttext',
            'label' => 'Combo',
            'entity' => '',
            'array_store' => '[{"key":"key1","value":"Wert1"},{"key":"key2","value":"Wert2"}]',
        ],
    ],
    8 => [
        'name' => 'integer2',
        'type' => 'int',
        '_locale' => 'de-DE',
    ],
    9 => [
        'name' => 'float2',
        'type' => 'float',
        '_locale' => 'de-DE',
    ],
];
