<?php declare(strict_types=1);

return array (
    0 =>
        array (
            'id' => '1',
            'password' => '$2y$10$h6bMe5mAYLQyFqPPOxE/XubVrMsojHmVX00aOkk3y0zIKC/G55hdG',
            'encoder' => 'bcrypt',
            'email' => 'max_mustermann@muster.de',
            'active' => '1',
            'accountmode' => '0',
            'confirmationkey' => '',
            'paymentID' => '5',
            'doubleOptinRegister' => '0',
            'doubleOptinEmailSentDate' => NULL,
            'doubleOptinConfirmDate' => NULL,
            'firstlogin' => '2018-08-09',
            'lastlogin' => '2018-08-09 15:12:38',
            'sessionID' => 'rb26jfdp4tlte4kf10cjam7g75',
            'newsletter' => '0',
            'validation' => '',
            'affiliate' => '0',
            'customergroup' => 'EK',
            'paymentpreset' => '0',
            'language' => '1',
            'subshopID' => '1',
            'referer' => '',
            'pricegroupID' => NULL,
            'internalcomment' => '',
            'failedlogins' => '0',
            'lockeduntil' => NULL,
            'default_billing_address_id' => '1',
            'default_shipping_address_id' => '1',
            'title' => NULL,
            'salutation' => 'mr',
            'firstname' => 'Max',
            'lastname' => 'Mustermann',
            'birthday' => NULL,
            'customernumber' => '20003',
            'login_token' => '04ff9402-39c3-4d5f-a754-b9e323014ab3.1',
            'changed' => '2018-08-09 15:12:33',
            'attributes' =>
                array (
                    'id' => '1',
                    'userID' => '1',
                ),
            'group' =>
                array (
                    'id' => '1',
                    'groupkey' => 'EK',
                    'description' => 'Shopkunden',
                    'tax' => '1',
                    'taxinput' => '1',
                    'mode' => '0',
                    'discount' => '0',
                    'minimumorder' => '0',
                    'minimumordersurcharge' => '0',
                ),
            'defaultpayment' =>
                array (
                    'id' => '5',
                    'name' => 'prepayment',
                    'description' => 'Vorkasse',
                    'template' => 'prepayment.tpl',
                    'class' => 'prepayment.php',
                    'table' => '',
                    'hide' => '0',
                    'additionaldescription' => 'Sie zahlen einfach vorab und erhalten die Ware bequem und günstig bei Zahlungseingang nach Hause geliefert.',
                    'debit_percent' => '0',
                    'surcharge' => '0',
                    'surchargestring' => '',
                    'position' => '1',
                    'active' => '1',
                    'esdactive' => '0',
                    'embediframe' => '',
                    'hideprospect' => '0',
                    'action' => NULL,
                    'pluginID' => NULL,
                    'source' => NULL,
                    'mobile_inactive' => '0',
                ),
            'customerlanguage' =>
                array (
                    'id' => '1',
                    'locale' => 'de_DE',
                    'language' => 'Deutsch',
                    'territory' => 'Deutschland',
                ),
            'shop' =>
                array (
                    'id' => '1',
                    'main_id' => NULL,
                    'name' => 'Deutsch',
                    'title' => NULL,
                    'position' => '0',
                    'host' => 'sw55.internal',
                    'base_path' => '',
                    'base_url' => NULL,
                    'hosts' => '',
                    'secure' => '0',
                    'template_id' => '22',
                    'document_template_id' => '22',
                    'category_id' => '3',
                    'locale_id' => '1',
                    'currency_id' => '1',
                    'customer_group_id' => '1',
                    'fallback_id' => NULL,
                    'customer_scope' => '0',
                    'default' => '1',
                    'active' => '1',
                ),
            '_locale' => 'de_DE',
            'addresses' =>
                array (
                    0 =>
                        array (
                            'id' => '1',
                            'user_id' => '1',
                            'company' => NULL,
                            'department' => NULL,
                            'salutation' => 'mr',
                            'title' => NULL,
                            'firstname' => 'Max',
                            'lastname' => 'Mustermann',
                            'street' => 'Examplestreet 11',
                            'zipcode' => '1234',
                            'city' => 'Schöppingen',
                            'country_id' => '2',
                            'state_id' => NULL,
                            'ustid' => NULL,
                            'phone' => NULL,
                            'additional_address_line1' => NULL,
                            'additional_address_line2' => NULL,
                            'attributes' =>
                                array (
                                    'id' => '1',
                                    'address_id' => '1',
                                    'text1' => NULL,
                                    'text2' => NULL,
                                    'text3' => NULL,
                                    'text4' => NULL,
                                    'text5' => NULL,
                                    'text6' => NULL,
                                ),
                            'country' =>
                                array (
                                    'id' => '2',
                                    'countryname' => 'Deutschland',
                                    'countryiso' => 'DE',
                                    'areaID' => '1',
                                    'countryen' => 'GERMANY',
                                    'position' => '1',
                                    'notice' => '',
                                    'taxfree' => '0',
                                    'taxfree_ustid' => '0',
                                    'taxfree_ustid_checked' => '0',
                                    'active' => '1',
                                    'iso3' => 'DEU',
                                    'display_state_in_registration' => '0',
                                    'force_state_in_registration' => '0',
                                ),
                        ),
                ),
        ),
    1 =>
        array (
            'id' => '2',
            'password' => '$2y$10$Hc4BqcaOt7nkEU6qu3W/z.pIkq3fbAFW/OwnlqHhvu9fGnhUT10pO',
            'encoder' => 'bcrypt',
            'email' => 'xyz@mail.com',
            'active' => '1',
            'accountmode' => '0',
            'confirmationkey' => '',
            'paymentID' => '5',
            'doubleOptinRegister' => '0',
            'doubleOptinEmailSentDate' => NULL,
            'doubleOptinConfirmDate' => NULL,
            'firstlogin' => '2018-08-09',
            'lastlogin' => '2018-08-09 15:12:51',
            'sessionID' => 'rb26jfdp4tlte4kf10cjam7g75',
            'newsletter' => '0',
            'validation' => '',
            'affiliate' => '0',
            'customergroup' => 'EK',
            'paymentpreset' => '0',
            'language' => '1',
            'subshopID' => '1',
            'referer' => '',
            'pricegroupID' => NULL,
            'internalcomment' => '',
            'failedlogins' => '0',
            'lockeduntil' => NULL,
            'default_billing_address_id' => '2',
            'default_shipping_address_id' => '2',
            'title' => NULL,
            'salutation' => 'mr',
            'firstname' => 'John',
            'lastname' => 'Doe',
            'birthday' => NULL,
            'customernumber' => '20004',
            'login_token' => '5b54308c-d097-4b69-9d6c-8e49eb631f5f.1',
            'changed' => '2018-08-09 15:12:49',
            'attributes' =>
                array (
                    'id' => '2',
                    'userID' => '2',
                ),
            'group' =>
                array (
                    'id' => '1',
                    'groupkey' => 'EK',
                    'description' => 'Shopkunden',
                    'tax' => '1',
                    'taxinput' => '1',
                    'mode' => '0',
                    'discount' => '0',
                    'minimumorder' => '0',
                    'minimumordersurcharge' => '0',
                ),
            'defaultpayment' =>
                array (
                    'id' => '5',
                    'name' => 'prepayment',
                    'description' => 'Vorkasse',
                    'template' => 'prepayment.tpl',
                    'class' => 'prepayment.php',
                    'table' => '',
                    'hide' => '0',
                    'additionaldescription' => 'Sie zahlen einfach vorab und erhalten die Ware bequem und günstig bei Zahlungseingang nach Hause geliefert.',
                    'debit_percent' => '0',
                    'surcharge' => '0',
                    'surchargestring' => '',
                    'position' => '1',
                    'active' => '1',
                    'esdactive' => '0',
                    'embediframe' => '',
                    'hideprospect' => '0',
                    'action' => NULL,
                    'pluginID' => NULL,
                    'source' => NULL,
                    'mobile_inactive' => '0',
                ),
            'customerlanguage' =>
                array (
                    'id' => '1',
                    'locale' => 'de_DE',
                    'language' => 'Deutsch',
                    'territory' => 'Deutschland',
                ),
            'shop' =>
                array (
                    'id' => '1',
                    'main_id' => NULL,
                    'name' => 'Deutsch',
                    'title' => NULL,
                    'position' => '0',
                    'host' => 'sw55.internal',
                    'base_path' => '',
                    'base_url' => NULL,
                    'hosts' => '',
                    'secure' => '0',
                    'template_id' => '22',
                    'document_template_id' => '22',
                    'category_id' => '3',
                    'locale_id' => '1',
                    'currency_id' => '1',
                    'customer_group_id' => '1',
                    'fallback_id' => NULL,
                    'customer_scope' => '0',
                    'default' => '1',
                    'active' => '1',
                ),
            '_locale' => 'de_DE',
            'addresses' =>
                array (
                    0 =>
                        array (
                            'id' => '2',
                            'user_id' => '2',
                            'company' => NULL,
                            'department' => NULL,
                            'salutation' => 'mr',
                            'title' => NULL,
                            'firstname' => 'John',
                            'lastname' => 'Doe',
                            'street' => 'Examplestreet 11',
                            'zipcode' => '1234',
                            'city' => 'Examplecity',
                            'country_id' => '2',
                            'state_id' => NULL,
                            'ustid' => NULL,
                            'phone' => NULL,
                            'additional_address_line1' => NULL,
                            'additional_address_line2' => NULL,
                            'attributes' =>
                                array (
                                    'id' => '2',
                                    'address_id' => '2',
                                    'text1' => NULL,
                                    'text2' => NULL,
                                    'text3' => NULL,
                                    'text4' => NULL,
                                    'text5' => NULL,
                                    'text6' => NULL,
                                ),
                            'country' =>
                                array (
                                    'id' => '2',
                                    'countryname' => 'Deutschland',
                                    'countryiso' => 'DE',
                                    'areaID' => '1',
                                    'countryen' => 'GERMANY',
                                    'position' => '1',
                                    'notice' => '',
                                    'taxfree' => '0',
                                    'taxfree_ustid' => '0',
                                    'taxfree_ustid_checked' => '0',
                                    'active' => '1',
                                    'iso3' => 'DEU',
                                    'display_state_in_registration' => '0',
                                    'force_state_in_registration' => '0',
                                ),
                        ),
                ),
        ),
);