<?php declare(strict_types=1);

return [
    0 => [
        'id' => '1',
        'group_id' => '6',
        'name' => 'rot',
        'position' => '8',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de_DE',
    ],
    1 => [
        'id' => '32',
        'group_id' => '5',
        'name' => '1,0 Liter',
        'position' => '3',
        'media_id' => null,
        'group' => [
            'id' => '5',
            'name' => 'Flascheninhalt',
            'description' => null,
            'position' => '3',
        ],
        '_locale' => 'de_DE',
    ],
    2 => [
        'id' => '33',
        'group_id' => '5',
        'name' => '1,5 Liter',
        'position' => '5',
        'media_id' => null,
        'group' => [
            'id' => '5',
            'name' => 'Flascheninhalt',
            'description' => null,
            'position' => '3',
        ],
        '_locale' => 'de_DE',
    ],
    3 => [
        'id' => '34',
        'group_id' => '5',
        'name' => '5 Liter',
        'position' => '6',
        'media_id' => null,
        'group' => [
            'id' => '5',
            'name' => 'Flascheninhalt',
            'description' => null,
            'position' => '3',
        ],
        '_locale' => 'de_DE',
    ],
    4 => [
        'id' => '35',
        'group_id' => '5',
        'name' => '0,5 Liter',
        'position' => '2',
        'media_id' => null,
        'group' => [
            'id' => '5',
            'name' => 'Flascheninhalt',
            'description' => null,
            'position' => '3',
        ],
        '_locale' => 'de_DE',
    ],
    5 => [
        'id' => '36',
        'group_id' => '6',
        'name' => 'grün',
        'position' => '9',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de_DE',
    ],
    6 => [
        'id' => '37',
        'group_id' => '6',
        'name' => 'pink',
        'position' => '10',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de_DE',
    ],
    7 => [
        'id' => '38',
        'group_id' => '6',
        'name' => 'gelb',
        'position' => '11',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de_DE',
    ],
    8 => [
        'id' => '39',
        'group_id' => '6',
        'name' => 'Signalrot',
        'position' => '12',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de_DE',
    ],
    9 => [
        'id' => '40',
        'group_id' => '6',
        'name' => 'Blau-Weiss',
        'position' => '13',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de_DE',
    ],
];
