<?php declare(strict_types=1);
/*
 * (c) shopware AG <info@shopware.com>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    0 => [
        'type' => 'option',
        'id' => '1',
        'group_id' => '6',
        'name' => 'Rot',
        'position' => '8',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de-DE',
    ],
    1 => [
        'type' => 'option',
        'id' => '32',
        'group_id' => '5',
        'name' => '1,0 Liter',
        'position' => '3',
        'media_id' => null,
        'group' => [
            'id' => '5',
            'name' => 'Flascheninhalt',
            'description' => null,
            'position' => '3',
        ],
        '_locale' => 'de-DE',
    ],
    2 => [
        'type' => 'option',
        'id' => '33',
        'group_id' => '5',
        'name' => '1,5 Liter',
        'position' => '5',
        'media_id' => null,
        'group' => [
            'id' => '5',
            'name' => 'Flascheninhalt',
            'description' => null,
            'position' => '3',
        ],
        '_locale' => 'de-DE',
    ],
    3 => [
        'type' => 'option',
        'id' => '34',
        'group_id' => '5',
        'name' => '5 Liter',
        'position' => '6',
        'media_id' => null,
        'group' => [
            'id' => '5',
            'name' => 'Flascheninhalt',
            'description' => null,
            'position' => '3',
        ],
        '_locale' => 'de-DE',
    ],
    4 => [
        'type' => 'option',
        'id' => '35',
        'group_id' => '5',
        'name' => '0,5 Liter',
        'position' => '2',
        'media_id' => null,
        'group' => [
            'id' => '5',
            'name' => 'Flascheninhalt',
            'description' => null,
            'position' => '3',
        ],
        '_locale' => 'de-DE',
    ],
    5 => [
        'type' => 'option',
        'id' => '36',
        'group_id' => '6',
        'name' => 'grün',
        'position' => '9',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de-DE',
    ],
    6 => [
        'type' => 'option',
        'id' => '37',
        'group_id' => '6',
        'name' => 'pink',
        'position' => '10',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de-DE',
    ],
    7 => [
        'type' => 'option',
        'id' => '38',
        'group_id' => '6',
        'name' => 'gelb',
        'position' => '11',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de-DE',
    ],
    8 => [
        'type' => 'option',
        'id' => '39',
        'group_id' => '6',
        'name' => 'Signalrot',
        'position' => '12',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de-DE',
    ],
    9 => [
        'type' => 'option',
        'id' => '40',
        'group_id' => '6',
        'name' => 'Blau-Weiss',
        'position' => '13',
        'media_id' => null,
        'group' => [
            'id' => '6',
            'name' => 'Farbe',
            'description' => null,
            'position' => '8',
        ],
        '_locale' => 'de-DE',
    ],
    10 => [
        'type' => 'property',
        'id' => '3',
        'name' => '16%',
        'position' => '0',
        'group' => [
            'id' => '1',
            'name' => 'Alkoholgehalt',
            'description' => 'Alkoholgehalt',
        ],
        'media' => [
            'id' => '772',
            'name' => 'bienenkleber',
            'description' => 'Nice Bienenkleber',
            'path' => 'media/image/bienenkleber.jpg',
            'file_size' => '21918',
            'albumID' => '-1',
            'attribute' => null,
        ],
        '_locale' => 'de-DE',
    ],
];
