<?php declare(strict_types=1);

return [
    0 => [
        'id' => '1',
        'email' => 'johndoe@shopware.com',
        'groupID' => '1',
        'salutation' => 'mr',
        'title' => '',
        'firstname' => 'John',
        'lastname' => 'Doe',
        'street' => 'test street',
        'zipcode' => '23232',
        'city' => 'Schoppingen',
        'added' => null,
        'double_optin_confirmed' => null,
        'deleted' => null,
        '_locale' => null,
    ],
    1 => [
        'id' => '1',
        'email' => 'janedoe@shopware.com',
        'groupID' => '1',
        'salutation' => 'xx',
        'title' => '',
        'firstname' => 'Jane',
        'lastname' => 'Doe',
        'street' => 'test street 2',
        'zipcode' => '4444',
        'city' => 'Schoppingen',
        'added' => null,
        'double_optin_confirmed' => '2019-04-11 12:45:40',
        'deleted' => null,
        '_locale' => null,
    ],
];
