<?php declare(strict_types=1);

namespace SwagMigrationAssistant\Migration\Logging;

final class LogType
{
    public const CONVERTER_NOT_FOUND = 'SWAG_MIGRATION__CONVERTER_NOT_FOUND';
    public const COULD_NOT_READ_ENTITY_COUNT = 'SWAG_MIGRATION__COULD_NOT_READ_ENTITY_COUNT';
    public const DATASET_NOT_FOUND = 'SWAG_MIGRATION__DATASET_NOT_FOUND';
    public const ENTITY_ALREADY_EXISTS = 'SWAG_MIGRATION__ENTITY_EXISTS';
    public const PROCESSOR_NOT_FOUND = 'SWAG_MIGRATION__PROCESSOR_NOT_FOUND';
    public const WRITER_NOT_FOUND = 'SWAG_MIGRATION__WRITER_NOT_FOUND';
    public const THEME_COMPILING_ERROR = 'SWAG_MIGRATION__THEME_COMPILING_ERROR';
}
