<?php declare(strict_types=1);

namespace SwagMigrationAssistant\Migration\Logging;

final class LogType
{
    public const ASSOCIATION_REQUIRED_MISSING = 'SWAG_MIGRATION__SHOPWARE_ASSOCIATION_REQUIRED_MISSING';
    public const CANNOT_CONVERT_CHILD_ENTITY = 'SWAG_MIGRATION_CANNOT_CONVERT_CHILD_ENTITY';
    public const CANNOT_CONVERT_ENTITY = 'SWAG_MIGRATION_CANNOT_CONVERT_ENTITY';
    public const CANNOT_GET_FILE = 'SWAG_MIGRATION_CANNOT_GET_FILE';
    public const CANNOT_COPY_MEDIA = 'SWAG_MIGRATION__SHOPWARE_CANNOT_COPY_DATA';
    public const CONVERTER_NOT_FOUND = 'SWAG_MIGRATION__CONVERTER_NOT_FOUND';
    public const COULD_NOT_READ_ENTITY_COUNT = 'SWAG_MIGRATION__COULD_NOT_READ_ENTITY_COUNT';
    public const DATASET_NOT_FOUND = 'SWAG_MIGRATION__DATASET_NOT_FOUND';
    public const EMPTY_NECESSARY_DATA_FIELDS = 'SWAG_MIGRATION__SHOPWARE_EMPTY_NECESSARY_DATA_FIELDS';
    public const ENTITY_ALREADY_EXISTS = 'SWAG_MIGRATION_ENTITY_ALREADY_EXISTS';
    public const ENTITY_FIELD_REASSIGNED = 'SWAG_MIGRATION_ENTITY_FIELD_REASSIGNED';
    public const ENTITY_UNKNOWN = 'SWAG_MIGRATION_ENTITY_UNKNOWN';
    public const PROCESSOR_NOT_FOUND = 'SWAG_MIGRATION__PROCESSOR_NOT_FOUND';
    public const RUN_EXCEPTION = 'SWAG_MIGRATION_RUN_EXCEPTION';
    public const WRITER_NOT_FOUND = 'SWAG_MIGRATION__WRITER_NOT_FOUND';
}
