<?php declare(strict_types=1);

namespace SwagMigrationNext\Profile\Shopware55\Logging;

final class LoggingType
{
    public const ASSOCIATION_REQUIRED_MISSING = 'SWAG-MIGRATION-SHOPWARE55-ASSOCIATION-REQUIRED-MISSING';
    public const CANNOT_PERSIST_MEDIA_FILE = 'SWAG-MIGRATION-CANNNOT-PERSIST-MEDIA-FILE';
    public const EMPTY_LOCALE = 'SWAG-MIGRATION-SHOPWARE55-EMPTY-LOCALE';
    public const EMPTY_NECESSARY_DATA_FIELDS = 'SWAG-MIGRATION-SHOPWARE55-EMPTY-NECESSARY-DATA-FIELDS';
    public const INVALID_UNSERIALIZED_DATA = 'SWAG-MIGRATION-SHOPWARE55-INVALID-UNSERIALIZED-DATA';
    public const NO_ADDRESS_DATA = 'SWAG-MIGRATION-SHOPWARE55-NO-ADDRESS-DATA';
    public const NO_DEFAULT_BILLING_AND_SHIPPING_ADDRESS = 'SWAG-MIGRATION-SHOPWARE55-NO-DEFAULT-BILLING-AND-SHIPPING-ADDRESS';
    public const NO_DEFAULT_BILLING_ADDRESS = 'SWAG-MIGRATION-SHOPWARE55-NO-DEFAULT-BILLING-ADDRESS';
    public const NO_DEFAULT_SHIPPING_ADDRESS = 'SWAG-MIGRATION-SHOPWARE55-NO-DEFAULT-SHIPPING-ADDRESS';
    public const NOT_CONVERTABLE_OBJECT_TYPE = 'SWAG-MIGRATION-SHOPWARE55-NOT-CONVERT-ABLE-OBJECT-TYPE';
    public const PRODUCT_MEDIA_NOT_CONVERTED = 'SWAG-MIGRATION-SHOPWARE55-PRODUCT-MEDIA-NOT-CONVERTED';
}
