<?php declare(strict_types=1);
/*
 * (c) shopware AG <info@shopware.com>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    [
        'detail' => [
            'id' => '43',
            'articleID' => '15',
            'ordernumber' => 'SW10015.1',
            'suppliernumber' => '',
            'kind' => '2',
            'additionaltext' => '',
            'sales' => '0',
            'active' => '1',
            'instock' => '0',
            'stockmin' => '0',
            'laststock' => '0',
            'weight' => null,
            'position' => '0',
            'width' => null,
            'height' => null,
            'length' => null,
            'ean' => '',
            'unitID' => null,
            'purchasesteps' => null,
            'maxpurchase' => null,
            'minpurchase' => '1',
            'purchaseunit' => null,
            'referenceunit' => null,
            'packunit' => '',
            'releasedate' => null,
            'shippingfree' => '0',
            'shippingtime' => '',
            'purchaseprice' => '0',
        ],
        'id' => '15',
        'supplierID' => '1',
        'name' => 'Dogs',
        'description' => '',
        'description_long' => '',
        'shippingtime' => null,
        'datum' => '2024-06-13',
        'active' => '1',
        'taxID' => '1',
        'pseudosales' => '0',
        'topseller' => '0',
        'metaTitle' => '',
        'keywords' => '',
        'changetime' => '2024-06-14 14:39:41',
        'pricegroupID' => null,
        'pricegroupActive' => '0',
        'filtergroupID' => null,
        'laststock' => '0',
        'crossbundlelook' => '0',
        'notification' => '0',
        'template' => '',
        'mode' => '0',
        'main_detail_id' => '42',
        'available_from' => null,
        'available_to' => null,
        'configurator_set_id' => '8',
        'tax' => [
            'id' => '1',
            'tax' => '19.00',
            'description' => '19%',
        ],
        'attributes' => [
            'id' => '32',
            'articledetailsID' => '43',
            'attr1' => '',
            'attr2' => '',
            'attr3' => '',
            'attr4' => null,
            'attr5' => null,
            'attr6' => null,
            'attr7' => null,
            'attr8' => null,
            'attr9' => null,
            'attr10' => null,
            'attr11' => null,
            'attr12' => null,
            'attr13' => null,
            'attr14' => null,
            'attr15' => null,
            'attr16' => null,
            'attr17' => null,
            'attr18' => null,
            'attr19' => null,
            'attr20' => null,
        ],
        'manufacturer' => [
            'id' => '1',
            'name' => 'Shopware Fashion',
            'img' => '',
            'link' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keywords' => '',
            'changed' => '2017-10-05 14:59:03',
        ],
        '_locale' => 'de-DE',
        'assets' => [
            [
                'id' => '73',
                'articleID' => null,
                'img' => 'lenkerenden-spiegel-rund-95-1',
                'main' => '2',
                'description' => '',
                'position' => '6',
                'width' => '0',
                'height' => '0',
                'relations' => '',
                'extension' => 'jpg',
                'parent_id' => '63',
                'article_detail_id' => '43',
                'media_id' => null,
                'media' => [
                    'id' => '33',
                    'albumID' => '-1',
                    'name' => 'lenkerenden-spiegel-rund-95-1',
                    'description' => '',
                    'path' => 'media/image/lenkerenden-spiegel-rund-95-1.jpg',
                    'type' => 'IMAGE',
                    'extension' => 'jpg',
                    'file_size' => '37567',
                    'width' => '432',
                    'height' => '324',
                    'userID' => '50',
                    'created' => '2024-06-13',
                    'uri' => 'https://migration5-kluetjann.shopdev.de/media/image/bb/e5/26/lenkerenden-spiegel-rund-95-1.jpg',
                ],
            ],
            [
                'id' => '74',
                'articleID' => null,
                'img' => 'dog-green',
                'main' => '2',
                'description' => '',
                'position' => '5',
                'width' => '0',
                'height' => '0',
                'relations' => '',
                'extension' => 'jpg',
                'parent_id' => '62',
                'article_detail_id' => '43',
                'media_id' => null,
                'media' => [
                    'id' => '28',
                    'albumID' => '-1',
                    'name' => 'dog-green',
                    'description' => '',
                    'path' => 'media/image/dog-green.jpg',
                    'type' => 'IMAGE',
                    'extension' => 'jpg',
                    'file_size' => '196885',
                    'width' => '512',
                    'height' => '512',
                    'userID' => '50',
                    'created' => '2024-06-13',
                    'uri' => 'https://migration5-kluetjann.shopdev.de/media/image/ac/c5/e1/dog-green.jpg',
                ],
            ],
            [
                'id' => '64',
                'articleID' => '15',
                'img' => 'lenkerenden-spiegel-rund-75-4',
                'main' => '1',
                'description' => '',
                'position' => '2',
                'width' => '0',
                'height' => '0',
                'relations' => '',
                'extension' => 'jpg',
                'parent_id' => null,
                'article_detail_id' => null,
                'media_id' => '32',
                'media' => [
                    'id' => '32',
                    'albumID' => '-1',
                    'name' => 'lenkerenden-spiegel-rund-75-4',
                    'description' => '',
                    'path' => 'media/image/lenkerenden-spiegel-rund-75-4.jpg',
                    'type' => 'IMAGE',
                    'extension' => 'jpg',
                    'file_size' => '277455',
                    'width' => '576',
                    'height' => '524',
                    'userID' => '50',
                    'created' => '2024-06-13',
                    'uri' => 'https://migration5-kluetjann.shopdev.de/media/image/23/aa/65/lenkerenden-spiegel-rund-75-4.jpg',
                ],
            ],
            [
                'id' => '65',
                'articleID' => '15',
                'img' => 'lenkerendenspiegel-ferr-schwarz-1',
                'main' => '2',
                'description' => '',
                'position' => '1',
                'width' => '0',
                'height' => '0',
                'relations' => '',
                'extension' => 'jpg',
                'parent_id' => null,
                'article_detail_id' => null,
                'media_id' => '31',
                'media' => [
                    'id' => '31',
                    'albumID' => '-1',
                    'name' => 'lenkerendenspiegel-ferr-schwarz-1',
                    'description' => '',
                    'path' => 'media/image/lenkerendenspiegel-ferr-schwarz-1.jpg',
                    'type' => 'IMAGE',
                    'extension' => 'jpg',
                    'file_size' => '31425',
                    'width' => '494',
                    'height' => '348',
                    'userID' => '50',
                    'created' => '2024-06-13',
                    'uri' => 'https://migration5-kluetjann.shopdev.de/media/image/81/65/d3/lenkerendenspiegel-ferr-schwarz-1.jpg',
                ],
            ],
        ],
        'categories' => [
            [
                'id' => '7',
                'path' => '|3|',
            ],
        ],
        'prices' => [
            [
                'id' => '51',
                'pricegroup' => 'EK',
                'from' => '1',
                'to' => 'beliebig',
                'articleID' => '15',
                'articledetailsID' => '43',
                'price' => '84.033613445378',
                'pseudoprice' => '0',
                'regulation_price' => '0',
                'baseprice' => null,
                'percent' => '0.00',
                'customergroup' => [
                    'id' => '1',
                    'groupkey' => 'EK',
                    'description' => 'Shopkunden',
                    'tax' => '1',
                    'taxinput' => '1',
                    'mode' => '0',
                    'discount' => '0',
                    'minimumorder' => '0',
                    'minimumordersurcharge' => '0',
                ],
                'currencyShortName' => 'EUR',
            ],
        ],
        'configuratorOptions' => [
            [
                'id' => '15',
                'group_id' => '5',
                'name' => 'Grün',
                'position' => '5',
                'media_id' => '0',
                'group' => [
                    'id' => '5',
                    'name' => 'Farbe',
                    'description' => null,
                    'position' => '1',
                ],
            ],
        ],
        'shops' => [
            '1',
        ],
    ],
    [
        'detail' => [
            'id' => '44',
            'articleID' => '15',
            'ordernumber' => 'SW10015.2',
            'suppliernumber' => '',
            'kind' => '2',
            'additionaltext' => '',
            'sales' => '0',
            'active' => '1',
            'instock' => '0',
            'stockmin' => '0',
            'laststock' => '0',
            'weight' => null,
            'position' => '0',
            'width' => null,
            'height' => null,
            'length' => null,
            'ean' => '',
            'unitID' => null,
            'purchasesteps' => null,
            'maxpurchase' => null,
            'minpurchase' => '1',
            'purchaseunit' => null,
            'referenceunit' => null,
            'packunit' => '',
            'releasedate' => null,
            'shippingfree' => '0',
            'shippingtime' => '',
            'purchaseprice' => '0',
        ],
        'id' => '15',
        'supplierID' => '1',
        'name' => 'Dogs',
        'description' => '',
        'description_long' => '',
        'shippingtime' => null,
        'datum' => '2024-06-13',
        'active' => '1',
        'taxID' => '1',
        'pseudosales' => '0',
        'topseller' => '0',
        'metaTitle' => '',
        'keywords' => '',
        'changetime' => '2024-06-14 14:39:41',
        'pricegroupID' => null,
        'pricegroupActive' => '0',
        'filtergroupID' => null,
        'laststock' => '0',
        'crossbundlelook' => '0',
        'notification' => '0',
        'template' => '',
        'mode' => '0',
        'main_detail_id' => '42',
        'available_from' => null,
        'available_to' => null,
        'configurator_set_id' => '8',
        'tax' => [
            'id' => '1',
            'tax' => '19.00',
            'description' => '19%',
        ],
        'attributes' => [
            'id' => '33',
            'articledetailsID' => '44',
            'attr1' => '',
            'attr2' => '',
            'attr3' => '',
            'attr4' => null,
            'attr5' => null,
            'attr6' => null,
            'attr7' => null,
            'attr8' => null,
            'attr9' => null,
            'attr10' => null,
            'attr11' => null,
            'attr12' => null,
            'attr13' => null,
            'attr14' => null,
            'attr15' => null,
            'attr16' => null,
            'attr17' => null,
            'attr18' => null,
            'attr19' => null,
            'attr20' => null,
        ],
        'manufacturer' => [
            'id' => '1',
            'name' => 'Shopware Fashion',
            'img' => '',
            'link' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keywords' => '',
            'changed' => '2017-10-05 14:59:03',
        ],
        '_locale' => 'de-DE',
        'assets' => [
            [
                'id' => '72',
                'articleID' => null,
                'img' => 'dog-pink',
                'main' => '2',
                'description' => '',
                'position' => '4',
                'width' => '0',
                'height' => '0',
                'relations' => '',
                'extension' => 'jpg',
                'parent_id' => '61',
                'article_detail_id' => '44',
                'media_id' => null,
                'media' => [
                    'id' => '29',
                    'albumID' => '-1',
                    'name' => 'dog-pink',
                    'description' => '',
                    'path' => 'media/image/dog-pink.jpg',
                    'type' => 'IMAGE',
                    'extension' => 'jpg',
                    'file_size' => '114526',
                    'width' => '512',
                    'height' => '512',
                    'userID' => '50',
                    'created' => '2024-06-13',
                    'uri' => 'https://migration5-kluetjann.shopdev.de/media/image/35/bc/57/dog-pink.jpg',
                ],
            ],
            [
                'id' => '64',
                'articleID' => '15',
                'img' => 'lenkerenden-spiegel-rund-75-4',
                'main' => '1',
                'description' => '',
                'position' => '2',
                'width' => '0',
                'height' => '0',
                'relations' => '',
                'extension' => 'jpg',
                'parent_id' => null,
                'article_detail_id' => null,
                'media_id' => '32',
                'media' => [
                    'id' => '32',
                    'albumID' => '-1',
                    'name' => 'lenkerenden-spiegel-rund-75-4',
                    'description' => '',
                    'path' => 'media/image/lenkerenden-spiegel-rund-75-4.jpg',
                    'type' => 'IMAGE',
                    'extension' => 'jpg',
                    'file_size' => '277455',
                    'width' => '576',
                    'height' => '524',
                    'userID' => '50',
                    'created' => '2024-06-13',
                    'uri' => 'https://migration5-kluetjann.shopdev.de/media/image/23/aa/65/lenkerenden-spiegel-rund-75-4.jpg',
                ],
            ],
            [
                'id' => '65',
                'articleID' => '15',
                'img' => 'lenkerendenspiegel-ferr-schwarz-1',
                'main' => '2',
                'description' => '',
                'position' => '1',
                'width' => '0',
                'height' => '0',
                'relations' => '',
                'extension' => 'jpg',
                'parent_id' => null,
                'article_detail_id' => null,
                'media_id' => '31',
                'media' => [
                    'id' => '31',
                    'albumID' => '-1',
                    'name' => 'lenkerendenspiegel-ferr-schwarz-1',
                    'description' => '',
                    'path' => 'media/image/lenkerendenspiegel-ferr-schwarz-1.jpg',
                    'type' => 'IMAGE',
                    'extension' => 'jpg',
                    'file_size' => '31425',
                    'width' => '494',
                    'height' => '348',
                    'userID' => '50',
                    'created' => '2024-06-13',
                    'uri' => 'https://migration5-kluetjann.shopdev.de/media/image/81/65/d3/lenkerendenspiegel-ferr-schwarz-1.jpg',
                ],
            ],
        ],
        'categories' => [
            [
                'id' => '7',
                'path' => '|3|',
            ],
        ],
        'prices' => [
            [
                'id' => '52',
                'pricegroup' => 'EK',
                'from' => '1',
                'to' => 'beliebig',
                'articleID' => '15',
                'articledetailsID' => '44',
                'price' => '84.033613445378',
                'pseudoprice' => '0',
                'regulation_price' => '0',
                'baseprice' => null,
                'percent' => '0.00',
                'customergroup' => [
                    'id' => '1',
                    'groupkey' => 'EK',
                    'description' => 'Shopkunden',
                    'tax' => '1',
                    'taxinput' => '1',
                    'mode' => '0',
                    'discount' => '0',
                    'minimumorder' => '0',
                    'minimumordersurcharge' => '0',
                ],
                'currencyShortName' => 'EUR',
            ],
        ],
        'configuratorOptions' => [
            [
                'id' => '16',
                'group_id' => '5',
                'name' => 'Pink',
                'position' => '6',
                'media_id' => '0',
                'group' => [
                    'id' => '5',
                    'name' => 'Farbe',
                    'description' => null,
                    'position' => '1',
                ],
            ],
        ],
        'shops' => [
            '1',
        ],
    ],
];
