<?php declare(strict_types=1);
/*
 * (c) shopware AG <info@shopware.com>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    [
        'id' => '15',
        'name' => 'Shop und CustomerGroup (Händler)',
        'type' => '0',
        'description' => '',
        'comment' => '',
        'active' => '0',
        'position' => '0',
        'calculation' => '0',
        'surcharge_calculation' => '0',
        'tax_calculation' => '0',
        'shippingfree' => null,
        'multishopID' => '1',
        'customergroupID' => '2',
        'bind_shippingfree' => '0',
        'bind_time_from' => null,
        'bind_time_to' => null,
        'bind_instock' => null,
        'bind_laststock' => '0',
        'bind_weekday_from' => null,
        'bind_weekday_to' => null,
        'bind_weight_from' => null,
        'bind_weight_to' => null,
        'bind_price_from' => null,
        'bind_price_to' => null,
        'bind_sql' => null,
        'status_link' => '',
        'calculation_sql' => null,
        'shop' => [
            'id' => '1',
            'main_id' => null,
            'name' => 'Demoshop',
            'title' => null,
            'position' => '0',
            'host' => 'sw55.local',
            'base_path' => '',
            'base_url' => null,
            'hosts' => 'sw55.local',
            'secure' => '0',
            'template_id' => '23',
            'document_template_id' => '23',
            'category_id' => '3',
            'locale_id' => '1',
            'currency_id' => '1',
            'customer_group_id' => '1',
            'fallback_id' => null,
            'customer_scope' => '0',
            'default' => '1',
            'active' => '1',
        ],
        'customerGroup' => [
            'id' => '2',
            'groupkey' => 'H',
            'description' => 'Händler',
            'tax' => '1',
            'taxinput' => '0',
            'mode' => '0',
            'discount' => '0',
            'minimumorder' => '0',
            'minimumordersurcharge' => '0',
        ],
        'shippingCosts' => [
            0 => [
                'id' => '309',
                'from' => '0.000',
                'value' => '0.00',
                'factor' => '0.00',
                'dispatchID' => '15',
                'currencyShortName' => 'EUR',
            ],
        ],
        '_locale' => 'de-DE',
    ],

    [
        'id' => '13',
        'name' => 'Nur CustomerGroup (Händler)',
        'type' => '0',
        'description' => '',
        'comment' => '',
        'active' => '0',
        'position' => '0',
        'calculation' => '2',
        'surcharge_calculation' => '0',
        'tax_calculation' => '0',
        'shippingfree' => null,
        'multishopID' => null,
        'customergroupID' => '2',
        'bind_shippingfree' => '0',
        'bind_time_from' => null,
        'bind_time_to' => null,
        'bind_instock' => null,
        'bind_laststock' => '0',
        'bind_weekday_from' => null,
        'bind_weekday_to' => null,
        'bind_weight_from' => null,
        'bind_weight_to' => null,
        'bind_price_from' => null,
        'bind_price_to' => null,
        'bind_sql' => null,
        'status_link' => '',
        'calculation_sql' => null,
        'customerGroup' => [
            'id' => '2',
            'groupkey' => 'H',
            'description' => 'Händler',
            'tax' => '1',
            'taxinput' => '0',
            'mode' => '0',
            'discount' => '0',
            'minimumorder' => '0',
            'minimumordersurcharge' => '0',
        ],
        'shippingCosts' => [
            0 => [
                'id' => '305',
                'from' => '0.000',
                'value' => '1000.00',
                'factor' => '0.00',
                'dispatchID' => '13',
                'currencyShortName' => 'EUR',
            ],
            1 => [
                'id' => '306',
                'from' => '101.000',
                'value' => '0.00',
                'factor' => '0.00',
                'dispatchID' => '13',
                'currencyShortName' => 'EUR',
            ],
        ],
        '_locale' => 'de-DE',
    ],

    [
        'id' => '11',
        'name' => 'Nur Shop',
        'type' => '0',
        'description' => '',
        'comment' => '',
        'active' => '0',
        'position' => '0',
        'calculation' => '1',
        'surcharge_calculation' => '0',
        'tax_calculation' => '0',
        'shippingfree' => null,
        'multishopID' => '1',
        'customergroupID' => null,
        'bind_shippingfree' => '0',
        'bind_time_from' => null,
        'bind_time_to' => null,
        'bind_instock' => null,
        'bind_laststock' => '0',
        'bind_weekday_from' => null,
        'bind_weekday_to' => null,
        'bind_weight_from' => null,
        'bind_weight_to' => null,
        'bind_price_from' => null,
        'bind_price_to' => null,
        'bind_sql' => null,
        'status_link' => '',
        'calculation_sql' => null,
        'shop' => [
            'id' => '1',
            'main_id' => null,
            'name' => 'Demoshop',
            'title' => null,
            'position' => '0',
            'host' => 'sw55.local',
            'base_path' => '',
            'base_url' => null,
            'hosts' => 'sw55.local',
            'secure' => '0',
            'template_id' => '23',
            'document_template_id' => '23',
            'category_id' => '3',
            'locale_id' => '1',
            'currency_id' => '1',
            'customer_group_id' => '1',
            'fallback_id' => null,
            'customer_scope' => '0',
            'default' => '1',
            'active' => '1',
        ],
        'shippingCosts' => [
            0 => [
                'id' => '297',
                'from' => '0.000',
                'value' => '50.00',
                'factor' => '0.00',
                'dispatchID' => '11',
                'currencyShortName' => 'EUR',
            ],
            1 => [
                'id' => '298',
                'from' => '100.010',
                'value' => '33.00',
                'factor' => '0.00',
                'dispatchID' => '11',
                'currencyShortName' => 'EUR',
            ],
            2 => [
                'id' => '299',
                'from' => '200.010',
                'value' => '0.00',
                'factor' => '0.00',
                'dispatchID' => '11',
                'currencyShortName' => 'EUR',
            ],
        ],
        '_locale' => 'de-DE',
    ],
];
