<?php declare(strict_types=1);
/*
 * (c) shopware AG <info@shopware.com>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    0 => [
        'id' => '1',
        'main_id' => null,
        'name' => 'Deutsch',
        'title' => null,
        'position' => '0',
        'host' => 'sw55.local',
        'base_path' => null,
        'base_url' => null,
        'hosts' => '',
        'secure' => '0',
        'template_id' => '23',
        'document_template_id' => '23',
        'category_id' => '3',
        'locale_id' => '1',
        'currency_id' => '5',
        'customer_group_id' => '1',
        'fallback_id' => null,
        'customer_scope' => '0',
        'default' => '1',
        'active' => '1',
        'locale' => 'de-DE',
        'currency' => 'EUR',
        '_locale' => 'de-DE',
        'children' => [
            0 => [
                'id' => '2',
                'main_id' => '1',
                'name' => 'English',
                'title' => 'English',
                'position' => '0',
                'host' => null,
                'base_path' => null,
                'base_url' => null,
                'hosts' => '',
                'secure' => '0',
                'template_id' => null,
                'document_template_id' => null,
                'category_id' => '39',
                'locale_id' => '2',
                'currency_id' => '5',
                'customer_group_id' => '1',
                'fallback_id' => '2',
                'customer_scope' => '0',
                'default' => '0',
                'active' => '1',
                'locale' => 'en-GB',
                'currency' => 'EUR',
                '_locale' => 'de-DE',
            ],
            1 => [
                'id' => '4',
                'main_id' => '1',
                'name' => 'Niederländisch',
                'title' => 'Niederländisch',
                'position' => '0',
                'host' => null,
                'base_path' => null,
                'base_url' => null,
                'hosts' => '',
                'secure' => '0',
                'template_id' => null,
                'document_template_id' => null,
                'category_id' => '3',
                'locale_id' => '176',
                'currency_id' => '5',
                'customer_group_id' => '1',
                'fallback_id' => null,
                'customer_scope' => '0',
                'default' => '0',
                'active' => '1',
                'locale' => 'nl-NL',
                'currency' => 'EUR',
                '_locale' => 'de-DE',
            ],
        ],
    ],
    1 => [
        'id' => '3',
        'main_id' => null,
        'name' => 'Gartensubshop',
        'title' => 'Gartensubshop',
        'position' => '0',
        'host' => 'garten.local',
        'base_path' => null,
        'base_url' => null,
        'hosts' => '',
        'secure' => '0',
        'template_id' => '22',
        'document_template_id' => '22',
        'category_id' => '39',
        'locale_id' => '32',
        'currency_id' => '5',
        'customer_group_id' => '1',
        'fallback_id' => null,
        'customer_scope' => '0',
        'default' => '0',
        'active' => '1',
        'locale' => 'bn-IN',
        'currency' => 'EUR',
        '_locale' => 'de-DE',
        'children' => [
            0 => [
                'id' => '5',
                'main_id' => '3',
                'name' => 'NL - Gartenshop',
                'title' => 'NL - Gartenshop',
                'position' => '0',
                'host' => null,
                'base_path' => null,
                'base_url' => null,
                'hosts' => '',
                'secure' => '0',
                'template_id' => null,
                'document_template_id' => null,
                'category_id' => '39',
                'locale_id' => '176',
                'currency_id' => '5',
                'customer_group_id' => '1',
                'fallback_id' => null,
                'customer_scope' => '0',
                'default' => '0',
                'active' => '1',
                'locale' => 'nl-NL',
                'currency' => 'EUR',
                '_locale' => 'de-DE',
            ],
        ],
    ],
];
