name: PHPUnit
description: Set up the extension and run PHPUnit

inputs:
    extension_name:
        required: true
        description: Extension directory name
    platform_branch:
        required: true
        description: Shopware version to install

runs:
    using: composite
    steps:
        - name: Setup extension
          uses: shopware/github-actions/setup-extension@main
          with:
              extensionName: ${{ inputs.extension_name }}
              install: true
              shopwareVersion: ${{ inputs.platform_branch }}
              extraRepositories: |
                  {
                    "${{ inputs.extension_name }}": {
                      "type": "path",
                      "url": "custom/plugins/${{ inputs.extension_name }}",
                      "symlink": true
                    }
                  }
        - name: Import SW5 TestData DB
          working-directory: custom/plugins/${{ inputs.extension_name }}/tests
          shell: bash
          run: mysql -uroot < _fixtures/database/shopware55.sql
        - name: Run PHPUnit
          working-directory: custom/plugins/${{ inputs.extension_name }}
          shell: bash
          run: php -d pcov.enabled=1 -d pcov.directory=${PWD} -d pcov.exclude='~(vendor|tests|node_modules)~' ${GITHUB_WORKSPACE}/vendor/bin/phpunit --configuration phpunit.xml.dist
