name: PHPStan
description: Set up the extension and run PHPStan

inputs:
    extension_name:
        required: true
        description: Extension directory name

runs:
    using: composite
    steps:
        - name: Setup extension
          uses: shopware/github-actions/setup-extension@main
          env:
              DATABASE_URL: mysql://root@127.0.0.1/shopware
          with:
              extensionName: ${{ inputs.extension_name }}
              install: true
              install-admin: true
              install-storefront: true
              extraRepositories: |
                  {
                    "${{ inputs.extension_name }}": {
                      "type": "path",
                      "url": "custom/plugins/${{ inputs.extension_name }}",
                      "symlink": true
                    }
                  }

        - name: Create phpstan.neon
          working-directory: custom/plugins/${{ inputs.extension_name }}
          shell: bash
          run: |
              printf "parameters:\n  tmpDir: ${GITHUB_WORKSPACE}/var/phpstan\nincludes:\n  - phpstan.neon.dist" > phpstan.neon

        - name: PHPStan cache
          uses: actions/cache@v4
          with:
              path: ${{ github.workspace }}/var/phpstan
              key: ${{ runner.os }}-${{ github.repository }}-phpstan-${{ github.sha }}
              restore-keys: |
                  ${{ runner.os }}-${{ github.repository }}-phpstan-

        - name: Build PHPStan Bootstrap
          shell: bash
          run: php ${GITHUB_WORKSPACE}/src/Core/DevOps/StaticAnalyze/phpstan-bootstrap.php

        - name: Run PHPStan
          shell: bash
          run: |
              composer -d custom/plugins/${{ inputs.extension_name }} dump-autoload --dev
              composer -d custom/plugins/${{ inputs.extension_name }} run phpstan
