import './swag-migration-index';
import './swag-migration-empty-screen';
import './swag-migration-main-page';
import './swag-migration-history';
import './swag-migration-history-detail';
import './swag-migration-history-detail-errors';
import './swag-migration-history-detail-data';
import './swag-migration-process-screen';
import './wizard';
