name: Acceptance
description: Set up the extension and run acceptance tests

inputs:
    extension_name:
        required: true
        description: Extension directory name
    platform_branch:
        required: true
        description: Shopware version to install
    update_snapshots:
        required: false
        default: 'false'
        description: Whether snapshots should be updated

runs:
    using: composite
    steps:
        - name: Cache npm
          uses: actions/cache@v4
          with:
              path: ~/.npm
              key: ${{ runner.os }}-acceptance-${{ hashFiles('tests/acceptance/package-lock.json') }}

        - name: Setup extension
          uses: shopware/github-actions/setup-extension@main
          with:
              extensionName: ${{ inputs.extension_name }}
              shopwareVersion: ${{ inputs.platform_branch }}
              install: true
              install-admin: true
              install-storefront: false
              mysqlVersion: skip
              env: prod
              extraRepositories: |
                  {
                    "${{ inputs.extension_name }}": {
                      "type": "path",
                      "url": "custom/plugins/${{ inputs.extension_name }}",
                      "symlink": true
                    }
                  }

        - name: Setup Migration Assistant
          shell: bash
          run: |
              composer run build:js:admin
              cd custom/plugins/${{ inputs.extension_name }}/tests
              mysql -uroot < _fixtures/database/shopware55corrupted.sql

        - name: Cache Playwright browsers
          uses: actions/cache@v4
          with:
              path: ~/.cache/ms-playwright
              key: playwright-${{ runner.os }}-${{ hashFiles('custom/plugins/**/tests/acceptance/package-lock.json') }}

        - name: Install playwright
          working-directory: custom/plugins/${{ inputs.extension_name }}/tests/acceptance
          shell: bash
          run: |
              npm ci
              npx playwright install --with-deps

        - name: Run Playwright
          working-directory: custom/plugins/${{ inputs.extension_name }}/tests/acceptance
          shell: bash
          env:
              DATABASE_URL: mysql://root:root@127.0.0.1:3306/shopware55
              UPDATE_SNAPSHOTS: ${{ inputs.update_snapshots }}
          run: npm run test

        - name: Upload test artifacts
          uses: actions/upload-artifact@v4
          if: always()
          with:
              name: e2e-${{ inputs.extension_name }}-${{ github.sha }}-${{ inputs.platform_branch }}
              path: |
                  custom/plugins/${{ inputs.extension_name }}/tests/acceptance/test-results/
                  custom/plugins/${{ inputs.extension_name }}/tests/acceptance/playwright-report/
              retention-days: 3

        - name: Upload updated snapshots
          if: inputs.update_snapshots == 'true'
          uses: actions/upload-artifact@v4
          with:
              name: visual-snapshots-${{ inputs.platform_branch }}
              path: custom/plugins/${{ inputs.extension_name }}/tests/acceptance/snapshots/
              retention-days: 3
