<?php declare(strict_types=1);

namespace SwagMigrationAssistant\Profile\Shopware\Logging;

final class LogType
{
    public const INVALID_UNSERIALIZED_DATA = 'SWAG_MIGRATION__SHOPWARE_INVALID_UNSERIALIZED_DATA';
    public const UNSUPPORTED_NUMBER_RANGE_TYPE = 'SWAG_MIGRATION__SHOPWARE_UNSUPPORTED_NUMBER_RANGE_TYPE';
    public const UNSUPPORTED_OBJECT_TYPE = 'SWAG_MIGRATION__SHOPWARE_UNSUPPORTED_OBJECT_TYPE';
}
