name: Acceptance

on:
  schedule:
    - cron: '0 3 * * *'  # nightly at 3 am utc
  workflow_dispatch:
    inputs:
      update_snapshots:
        description: 'Update snapshots'
        required: false
        type: boolean
        default: true
  push:
    branches:
      - trunk
  pull_request:
    paths:
      - src/**
      - tests/acceptance/**
      - .github/workflows/acceptance.yaml

jobs:
  playwright:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PLATFORM_BRANCH: ["trunk"]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: shopware
        ports:
          - 3306:3306
    env:
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/shopware

    steps:
      - uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: ${{ github.event.repository.name }}
          shopwareVersion: ${{ matrix.PLATFORM_BRANCH }}
          install: true
          install-admin: true
          install-storefront: false
          mysqlVersion: skip
          env: prod
          extraRepositories: |
            {
              "${{ github.event.repository.name }}": {
                "type": "path",
                "url": "custom/plugins/${{ github.event.repository.name }}",
                "symlink": true
              }
            }

      - name: Setup Migration Assistant
        run: |
          composer run build:js:admin
          cd custom/plugins/${{ github.event.repository.name }}/tests
          mysql -uroot < _fixtures/database/shopware55.sql

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('custom/plugins/**/tests/acceptance/package-lock.json') }}

      - name: Install playwright
        working-directory: custom/plugins/${{ github.event.repository.name }}/tests/acceptance
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright
        working-directory: custom/plugins/${{ github.event.repository.name }}/tests/acceptance
        env:
          DATABASE_URL: mysql://root:root@127.0.0.1:3306/shopware55
          UPDATE_SNAPSHOTS: ${{ github.event.inputs.update_snapshots == 'true' && '1' || '' }}
        run: npm run test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-${{ github.event.repository.name }}-${{ github.sha }}-${{ matrix.PLATFORM_BRANCH }}
          path: |
            custom/plugins/${{ github.event.repository.name }}/tests/acceptance/test-results/
            custom/plugins/${{ github.event.repository.name }}/tests/acceptance/playwright-report/
          retention-days: 3

      - name: Upload updated snapshots
        if: github.event.inputs.update_snapshots == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: visual-snapshots-${{ matrix.PLATFORM_BRANCH }}
          path: custom/plugins/${{ github.event.repository.name }}/tests/acceptance/snapshots/
          retention-days: 3
