name: Reusable PHPUnit

on:
    workflow_call:
        inputs:
            extension_name:
                required: true
                type: string
            platform_branch:
                required: true
                type: string
            coverage:
                required: false
                type: boolean
                default: false
        secrets:
            CODECOV_TOKEN:
                required: false

jobs:
    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - name: Setup extension
              uses: shopware/github-actions/setup-extension@main
              with:
                  extensionName: ${{ inputs.extension_name }}
                  install: true
                  shopwareVersion: ${{ inputs.platform_branch }}
                  extraRepositories: |
                      {
                        "${{ inputs.extension_name }}": {
                          "type": "path",
                          "url": "custom/plugins/${{ inputs.extension_name }}",
                          "symlink": true
                        }
                      }

            - name: Import SW5 test data DB
              working-directory: custom/plugins/${{ inputs.extension_name }}/tests
              run: mysql -uroot < _fixtures/database/shopware55.sql

            - name: Run PHPUnit
              run: composer -d custom/plugins/${{ inputs.extension_name }} run phpunit -- ${{ inputs.coverage && '--coverage-clover clover.xml' || '' }}

            - name: Upload coverage to Codecov
              if: inputs.coverage
              uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              with:
                  root_dir: ${{ github.workspace }}/custom/plugins/${{ inputs.extension_name }}
                  working-directory: ${{ github.workspace }}/custom/plugins/${{ inputs.extension_name }}
                  files: ./clover.xml
