name: Reusable PHPStan

on:
    workflow_call:
        inputs:
            extension_name:
                required: true
                type: string

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - name: Setup extension
              uses: shopware/github-actions/setup-extension@main
              env:
                  DATABASE_URL: mysql://root@127.0.0.1/shopware
              with:
                  extensionName: ${{ inputs.extension_name }}
                  install: true
                  install-admin: true
                  install-storefront: true
                  extraRepositories: |
                      {
                        "${{ inputs.extension_name }}": {
                          "type": "path",
                          "url": "custom/plugins/${{ inputs.extension_name }}",
                          "symlink": true
                        }
                      }

            - name: Create phpstan.neon
              working-directory: custom/plugins/${{ inputs.extension_name }}
              run: |
                  printf "parameters:\n  tmpDir: ${GITHUB_WORKSPACE}/var/phpstan\nincludes:\n  - phpstan.neon.dist" > phpstan.neon

            - name: PHPStan cache
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              with:
                  path: ${{ github.workspace }}/var/phpstan
                  key: ${{ runner.os }}-${{ github.repository }}-phpstan-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-${{ github.repository }}-phpstan-

            - name: Build PHPStan bootstrap
              run: php ${GITHUB_WORKSPACE}/src/Core/DevOps/StaticAnalyze/phpstan-bootstrap.php

            - name: Run PHPStan
              run: |
                  composer -d custom/plugins/${{ inputs.extension_name }} dump-autoload --dev
                  composer -d custom/plugins/${{ inputs.extension_name }} run phpstan
