name: Reusable Jest

on:
    workflow_call:
        inputs:
            extension_name:
                required: true
                type: string

jobs:
    jest:
        name: Jest
        runs-on: ubuntu-latest
        env:
            ARTIFACTS_PATH: ${{ github.workspace }}/development
        steps:
            - name: Cache npm
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-jest-${{ hashFiles('tests/Jest/package-lock.json') }}

            - name: Setup extension
              uses: shopware/github-actions/setup-extension@main
              with:
                  extensionName: ${{ inputs.extension_name }}
                  install: true
                  install-admin: true
                  install-storefront: false
                  extraRepositories: |
                      {
                        "${{ inputs.extension_name }}": {
                          "type": "path",
                          "url": "custom/plugins/${{ inputs.extension_name }}",
                          "symlink": true
                        }
                      }

            - name: Install Jest dependencies
              working-directory: custom/plugins/${{ inputs.extension_name }}/tests/Jest
              run: npm ci

            - name: Run Jest
              working-directory: custom/plugins/${{ inputs.extension_name }}/tests/Jest
              run: npm run unit
