name: Admin

env:
    EXTENSION_NAME: ${{ github.event.repository.name }}

on:
    workflow_dispatch:
    push:
        branches:
            - trunk
    pull_request:
        paths:
            - src/Resources/app/administration/**
            - tests/Jest/**
            - .github/workflows/**
            - '**/*.md'

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint and formatting checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Setup Node.js
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 20
                  cache: npm
                  cache-dependency-path: |
                      src/Resources/app/administration/package-lock.json
                      tests/Jest/package-lock.json
                      tests/acceptance/package-lock.json

            - name: Install admin dependencies
              run: |
                  npm ci --prefix src/Resources/app/administration
                  npm ci --prefix tests/Jest
                  npm ci --prefix tests/acceptance

            - name: Run lint and formatting checks
              run: |
                  npm run lint --prefix tests/Jest
                  npm run lint --prefix src/Resources/app/administration
                  npm run lint --prefix tests/acceptance
                  npm run lint:scss --prefix src/Resources/app/administration
                  npm run format --prefix tests/Jest
                  npm run format --prefix src/Resources/app/administration
                  npm run format --prefix tests/acceptance
                  npm run format:md --prefix src/Resources/app/administration
                  npm run format:yml --prefix src/Resources/app/administration

    jest:
        name: Jest
        uses: ./.github/workflows/action-jest.yml
        with:
            extension_name: ${{ github.event.repository.name }}
