name: Integration

env:
    EXTENSION_NAME: ${{ github.event.repository.name }}
    PLATFORM_BRANCH: trunk

on:
    workflow_dispatch:
    push:
        branches:
            - trunk
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    danger:
        name: Danger Check
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Checkout repository
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Run Danger PHP
              uses: docker://ghcr.io/shyim/danger-php:latest
              with:
                  args: ci
              env:
                  GITHUB_REPOSITORY: ${{ github.repository }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}

    build_zip:
        name: Build and validate zip
        runs-on: ubuntu-latest
        steps:
            - name: Build
              uses: shopware/github-actions/build-zip@main
              with:
                  extensionName: ${{ env.EXTENSION_NAME }}

    phpunit:
        name: PHPUnit
        uses: ./.github/workflows/action-phpunit.yml
        with:
            extension_name: ${{ github.event.repository.name }}
            platform_branch: trunk

    smoke_test:
        name: Smoke test
        runs-on: ubuntu-latest
        steps:
            - name: Setup extension
              uses: shopware/github-actions/setup-extension@main
              with:
                  extensionName: ${{ env.EXTENSION_NAME }}
                  shopwareVersion: ${{ env.PLATFORM_BRANCH }}
                  install: true
                  install-admin: true
                  install-storefront: true
                  extraRepositories: |
                      {
                        "${{ env.EXTENSION_NAME }}": {
                          "type": "path",
                          "url": "custom/plugins/${{ env.EXTENSION_NAME }}",
                          "symlink": true
                        }
                      }

            - name: Uninstall Plugin
              run: php bin/console plugin:uninstall ${{ env.EXTENSION_NAME }}
