name: Integration

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  danger:
    name: Danger Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Danger PHP
        uses: docker://ghcr.io/shyim/danger-php:latest
        with:
          args: ci
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}

  build_zip:
    name: Build and validate zip
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: shopware/github-actions/build-zip@main
        with:
          extensionName: ${{ github.event.repository.name }}

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PLATFORM_BRANCH: ["trunk"] # TODO add min version 6.7.0 here when trunk becomes > 6.7.0
    steps:
      - uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: ${{ github.event.repository.name }}
          install: true
          shopwareVersion: ${{ matrix.PLATFORM_BRANCH }}
          extraRepositories: |
            {
              "${{ github.event.repository.name }}": {
                "type": "path",
                "url": "custom/plugins/${{ github.event.repository.name }}",
                "symlink": true
              }
            }
      - name: Import SW5 TestData DB
        working-directory: custom/plugins/${{ github.event.repository.name }}/tests
        run: mysql -uroot < _fixtures/database/sw55.sql
      - name: Run PHPUnit
        working-directory: custom/plugins/${{ github.event.repository.name }}
        run: php -d pcov.enabled=1 -d pcov.directory=${PWD} -d pcov.exclude='~(vendor|tests|node_modules)~' ${GITHUB_WORKSPACE}/vendor/bin/phpunit --configuration phpunit.xml.dist

  smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: ${{ github.event.repository.name }}
          install: true
          install-admin: true
          install-storefront: true
          extraRepositories: |
            {
              "${{ github.event.repository.name }}": {
                "type": "path",
                "url": "custom/plugins/${{ github.event.repository.name }}",
                "symlink": true
              }
            }
      - name: Uninstall Plugin
        run: php bin/console plugin:uninstall ${{ github.event.repository.name }}
