name: PHP Checks

on:
    workflow_dispatch:
    push:
        branches:
            - trunk
    pull_request:
        paths:
            - composer.json
            - src/**/*.php
            - tests/**/*.php
            - .github/workflows/**

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: PHP checks
        uses: ./.github/workflows/action-lint.yml
        with:
            extension_name: ${{ github.event.repository.name }}
            run_php: true
