name: PHP Checks

on:
    workflow_dispatch:
    push:
        branches:
            - trunk
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    codestyle_php:
        name: Codestyle PHP
        runs-on: ubuntu-latest
        steps:
            - uses: shopware/github-actions/cs-fixer@main
              with:
                  rules: ''

    phpstan:
        name: PHPStan
        uses: ./.github/workflows/action-phpstan.yml
        with:
            extension_name: ${{ github.event.repository.name }}

    extension_verifier:
        name: Extension Verifier (lowest)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout SwagMigrationAssistant
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Remove PHPStan config
              run: rm phpstan.neon.dist

            - name: Allow composer to resolve advisory-affected releases
              run: composer config policy.advisories.block false

            - name: Run verifier
              uses: shopware/github-actions/extension-verifier@main
              with:
                  action: check
                  check-against: lowest
