<?php declare(strict_types=1);
/*
 * (c) shopware AG <info@shopware.com>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    [
        'detail' => [
            'id' => '6',
            'articleID' => '6',
            'ordernumber' => 'SW10006',
            'suppliernumber' => '',
            'kind' => '1',
            'additionaltext' => '',
            'sales' => '0',
            'active' => '1',
            'instock' => '50',
            'stockmin' => '3',
            'laststock' => '0',
            'weight' => '0.150',
            'position' => '0',
            'width' => null,
            'height' => null,
            'length' => null,
            'ean' => '',
            'unitID' => '9',
            'purchasesteps' => null,
            'maxpurchase' => null,
            'minpurchase' => '1',
            'purchaseunit' => '1.0000',
            'referenceunit' => '1.000',
            'packunit' => '',
            'releasedate' => null,
            'shippingfree' => '1',
            'shippingtime' => '',
            'purchaseprice' => '0',
        ],
        'id' => '6',
        'supplierID' => '1',
        'name' => 'Hauptartikel mit Kennzeichnung Versandkostenfrei und Hervorhebung',
        'description' => '',
        'description_long' => '<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>',
        'shippingtime' => null,
        'datum' => '2017-10-05',
        'active' => '1',
        'taxID' => '1',
        'pseudosales' => '0',
        'topseller' => '1',
        'metaTitle' => '',
        'keywords' => '',
        'changetime' => '2017-10-10 10:04:10',
        'pricegroupID' => null,
        'pricegroupActive' => '0',
        'filtergroupID' => '1',
        'laststock' => '0',
        'crossbundlelook' => '0',
        'notification' => '0',
        'template' => '',
        'mode' => '0',
        'main_detail_id' => '6',
        'available_from' => null,
        'available_to' => null,
        'configurator_set_id' => null,
        'unit' => [
            'id' => '9',
            'unit' => 'Stck.',
            'description' => 'Stück',
        ],
        'tax' => [
            'id' => '1',
            'tax' => '19.00',
            'description' => '19%',
        ],
        'attributes' => [
            'id' => '6',
            'articleID' => null,
            'articledetailsID' => '6',
            'attr1' => '',
            'attr2' => '',
            'attr3' => '',
            'attr4' => null,
            'attr5' => null,
            'attr6' => null,
            'attr7' => null,
            'attr8' => null,
            'attr9' => null,
            'attr10' => null,
            'attr11' => null,
            'attr12' => null,
            'attr13' => null,
            'attr14' => null,
            'attr15' => null,
            'attr16' => null,
            'attr17' => null,
            'attr18' => null,
            'attr19' => null,
            'attr20' => null,
        ],
        'manufacturer' => [
            'id' => '1',
            'name' => 'Shopware Fashion',
            'img' => '',
            'link' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keywords' => '',
            'changed' => '2017-10-05 14:59:03',
        ],
        '_locale' => 'de-DE',
        'categories' => [
            0 => [
                'id' => '12',
            ],
        ],
        'prices' => [
            0 => [
                'id' => '6',
                'pricegroup' => 'EK',
                'from' => '1',
                'to' => 'beliebig',
                'articleID' => '6',
                'articledetailsID' => '6',
                'price' => '12.605042016807',
                'pseudoprice' => '0',
                'baseprice' => null,
                'percent' => '0.00',
                'customergroup' => [
                    'id' => '1',
                    'groupkey' => 'EK',
                    'description' => 'Shopkunden',
                    'tax' => '1',
                    'taxinput' => '1',
                    'mode' => '0',
                    'discount' => '0',
                    'minimumorder' => '10',
                    'minimumordersurcharge' => '5',
                ],
                'currencyShortName' => 'EUR',
            ],
        ],
        'assets' => [
            0 => [
                'id' => '6',
                'articleID' => '6',
                'img' => 'handschuh',
                'main' => '1',
                'description' => 'Nicer Handschuh',
                'position' => '1',
                'width' => '0',
                'height' => '0',
                'relations' => '',
                'extension' => 'jpg',
                'parent_id' => null,
                'article_detail_id' => null,
                'media_id' => '4',
                'media' => [
                    'id' => '4',
                    'albumID' => '-1',
                    'name' => 'handschuh',
                    'description' => '',
                    'path' => 'media/image/handschuh.jpg',
                    'type' => 'IMAGE',
                    'extension' => 'jpg',
                    'file_size' => '57069',
                    'width' => '1280',
                    'height' => '1280',
                    'userID' => '50',
                    'created' => '2017-10-05',
                    'album' => [
                        'id' => '-1',
                        'name' => 'Artikel',
                        'parentID' => null,
                        'position' => '2',
                        'garbage_collectable' => '1',
                        'settings' => [
                            'id' => '10',
                            'albumID' => '-1',
                            'create_thumbnails' => '1',
                            'thumbnail_size' => '200x200;600x600;1280x1280',
                            'icon' => 'sprite-inbox',
                            'thumbnail_high_dpi' => '1',
                            'thumbnail_quality' => '90',
                            'thumbnail_high_dpi_quality' => '60',
                        ],
                    ],
                    'uri' => 'http://sw55.internal/media/image/02/ba/72/handschuh.jpg',
                ],
            ],
        ],
        'esdFiles' => [
            [
                'id' => '5',
                'name' => '10099855.jpg',
                'path' => 's:33:"552211cce724117c3178e3d22bec532ec";',
            ],
        ],
        'mainCategories' => [
            [
                'shopId' => '1',
                'categoryId' => '15',
            ],
            [
                'shopId' => '3',
                'categoryId' => '51',
            ],
        ],
    ],
];
